import type { AgentDetail, PermissionEntry } from "./passport-cache.js";

function formatConstraints(p: PermissionEntry): string[] {
  const lines: string[] = [];
  if (p.constraints?.maxAmount) lines.push(`max $${p.constraints.maxAmount}`);
  if (p.constraints?.allowedVendors?.length) lines.push(`vendors: ${p.constraints.allowedVendors.join(", ")}`);
  if (p.constraints?.expiresAt) lines.push(`expires: ${p.constraints.expiresAt.slice(0, 10)}`);
  return lines;
}

export function generateContextMd(detail: AgentDetail, updatedAt?: string): string {
  const { agent, permissions } = detail;
  const active = permissions.filter(p => p.status === "active");
  const guidelines = agent.guidelines ?? [];
  const timestamp = updatedAt ?? new Date().toISOString().slice(0, 16).replace("T", " ");

  const lines = [
    `<!-- BehalfID Agent Context — auto-generated by \`behalf mcp init\` -->`,
    `<!-- Run \`behalf mcp init --refresh\` to update -->`,
    ``,
    `## BehalfID Agent: ${agent.name}`,
    ``,
    `You are operating as BehalfID agent **\`${agent.agentId}\`** ("${agent.name}").`,
    ``,
    `The \`behalfid\` MCP server is active in this session.`,
    ``,
    `**ENFORCEMENT RULE: Before executing any risky, external, state-changing,`,
    `permissioned, or potentially sensitive action, you MUST call the \`verify_action\``,
    `tool from the \`behalfid\` MCP server.**`,
    ``,
    `Fail closed — follow these rules exactly:`,
    ``,
    `- If \`verify_action\` returns \`"allowed": false\` and \`"approvalRequired": false\`,`,
    `  do not execute the action. Explain the denial reason to the user.`,
    `- If \`verify_action\` is unavailable, errors, or cannot be reached, do not execute the action.`,
    `- If \`verify_action\` returns \`"approvalRequired": true\`:`,
    `  1. Do NOT execute the action under any circumstances.`,
    `  2. Tell the user the action requires approval and provide the \`approvalId\` and \`requestId\`.`,
    `  3. Direct them to the BehalfID Approvals dashboard to approve the request.`,
    `  4. Wait for the user to confirm they have approved.`,
    `  5. Call \`verify_action\` again with the same arguments.`,
    `  6. If it returns \`"allowed": true\`, proceed. If still \`"approvalRequired": true\`, wait longer.`,
    `- Never bypass, ignore, or replace the BehalfID check with a local guess.`,
    ``,
  ];

  if (active.length === 0) {
    lines.push(`### Permissions`, ``, `No active permissions. All external actions will be denied.`, ``);
  } else {
    lines.push(`### Active Permissions`, ``);
    for (const p of active) {
      const constraints = formatConstraints(p);
      const constraintStr = constraints.length ? ` (${constraints.join(", ")})` : "";
      lines.push(`- **${p.action}**${p.resource ? ` → \`${p.resource}\`` : ""}${constraintStr}${p.scope ? `: ${p.scope}` : ""}`);

      if (p.allowedActions?.length) {
        lines.push(`  - Allowed: ${p.allowedActions.map(a => `"${a}"`).join(", ")}`);
      }
      if (p.blockedActions?.length) {
        lines.push(`  - Blocked: ${p.blockedActions.map(a => `"${a}"`).join(", ")}`);
      }
      if (p.requiresApproval) {
        lines.push(`  - Approval required: pause for human approval before proceeding`);
      }
    }
    lines.push(``);
  }

  const blocked = active.filter(p => p.blockedActions?.length);
  if (blocked.length > 0) {
    lines.push(`### Blocked Actions`, ``);
    for (const p of blocked) {
      lines.push(`- **${p.action}**${p.resource ? ` on \`${p.resource}\`` : ""}: ${p.blockedActions?.map(a => `"${a}"`).join(", ")}`);
    }
    lines.push(``);
  }

  const approvalRequired = active.filter(p => p.requiresApproval);
  if (approvalRequired.length > 0) {
    lines.push(`### Approval-Required Actions`, ``);
    lines.push(`These actions require a human to approve before execution. When \`verify_action\` returns`, `\`"approvalRequired": true\`, stop and follow the approval protocol above.`, ``);
    for (const p of approvalRequired) {
      lines.push(`- **${p.action}**${p.resource ? ` on \`${p.resource}\`` : ""}: requires human approval via BehalfID dashboard before execution.`);
    }
    lines.push(``);
  }

  if (guidelines.length > 0) {
    lines.push(`### Guidelines`, ``);
    for (const g of guidelines) {
      lines.push(`- ${g}`);
    }
    lines.push(``);
  }

  lines.push(
    `### How to call \`verify_action\``,
    ``,
    `\`\`\``,
    `verify_action(action: string, vendor?: string, amount?: number)`,
    `// action: "deploy_production" | "purchase" | "access_data" | "browse_web" | ...`,
    `// vendor: the service or domain (e.g. "vercel.com", "amazon.com", "github.com")`,
    `// amount: only for purchase actions`,
    `\`\`\``,
    ``,
    `Possible responses:`,
    ``,
    `\`\`\`json`,
    `// Allowed`,
    `{ "allowed": true, "approvalRequired": false, "reason": "...", "risk": "low" }`,
    ``,
    `// Denied`,
    `{ "allowed": false, "approvalRequired": false, "reason": "...", "risk": "high" }`,
    ``,
    `// Approval required — STOP and follow the approval protocol`,
    `{ "allowed": false, "approvalRequired": true, "approvalId": "apr_xxx", "requestId": "req_xxx",`,
    `  "reason": "Permission requires approval before execution.", "risk": "medium" }`,
    `\`\`\``,
    ``,
    `---`,
    `*Updated ${timestamp} · Agent \`${agent.agentId}\` · [BehalfID](https://www.behalfid.com)*`
  );

  return lines.join("\n");
}

export function generateMcpJson(existing?: Record<string, unknown>): string {
  const base = existing ?? {};
  const servers = (base.mcpServers as Record<string, unknown> | undefined) ?? {};

  const updated = {
    ...base,
    mcpServers: {
      ...servers,
      behalfid: {
        type: "stdio",
        command: "behalf",
        args: ["mcp", "start"],
      },
    },
  };

  return JSON.stringify(updated, null, 2) + "\n";
}
