import type { AgentDetail, PermissionEntry } from "./passport-cache.js";

function formatConstraints(p: PermissionEntry): string[] {
  const lines: string[] = [];
  if (p.constraints?.maxAmount) lines.push(`max $${p.constraints.maxAmount}`);
  if (p.constraints?.allowedVendors?.length) lines.push(`vendors: ${p.constraints.allowedVendors.join(", ")}`);
  if (p.constraints?.expiresAt) lines.push(`expires: ${p.constraints.expiresAt.slice(0, 10)}`);
  return lines;
}

export function generateContextMd(detail: AgentDetail, updatedAt?: string): string {
  const { agent, permissions } = detail;
  const active = permissions.filter(p => p.status === "active");
  const guidelines = agent.guidelines ?? [];
  const timestamp = updatedAt ?? new Date().toISOString().slice(0, 16).replace("T", " ");

  const lines = [
    `<!-- BehalfID Agent Context — auto-generated by \`behalf mcp init\` -->`,
    `<!-- Run \`behalf mcp init --refresh\` to update -->`,
    ``,
    `## BehalfID Agent: ${agent.name}`,
    ``,
    `You are operating as BehalfID agent **\`${agent.agentId}\`** ("${agent.name}").`,
    ``,
    `The \`behalfid\` MCP server is active in this session.`,
    ``,
    `**ENFORCEMENT RULE: Before executing any risky, external, state-changing,`,
    `permissioned, or potentially sensitive action, you MUST call the \`verify_action\``,
    `tool from the \`behalfid\` MCP server.**`,
    ``,
    `Fail closed:`,
    ``,
    `- If \`verify_action\` returns \`"allowed": false\`, do not execute the action.`,
    `- If \`verify_action\` is unavailable, errors, or cannot be reached, do not execute the action.`,
    `- If the decision says approval is required, pause for human approval; do not execute automatically.`,
    `- Never bypass, ignore, or replace the BehalfID check with a local guess.`,
    ``,
  ];

  if (active.length === 0) {
    lines.push(`### Permissions`, ``, `No active permissions. All external actions will be denied.`, ``);
  } else {
    lines.push(`### Active Permissions`, ``);
    for (const p of active) {
      const constraints = formatConstraints(p);
      const constraintStr = constraints.length ? ` (${constraints.join(", ")})` : "";
      lines.push(`- **${p.action}**${p.resource ? ` → \`${p.resource}\`` : ""}${constraintStr}${p.scope ? `: ${p.scope}` : ""}`);

      if (p.allowedActions?.length) {
        lines.push(`  - Allowed: ${p.allowedActions.map(a => `"${a}"`).join(", ")}`);
      }
      if (p.blockedActions?.length) {
        lines.push(`  - Blocked: ${p.blockedActions.map(a => `"${a}"`).join(", ")}`);
      }
      if (p.requiresApproval) {
        lines.push(`  - Approval required: pause for human approval before proceeding`);
      }
    }
    lines.push(``);
  }

  const blocked = active.filter(p => p.blockedActions?.length);
  if (blocked.length > 0) {
    lines.push(`### Blocked Actions`, ``);
    for (const p of blocked) {
      lines.push(`- **${p.action}**${p.resource ? ` on \`${p.resource}\`` : ""}: ${p.blockedActions?.map(a => `"${a}"`).join(", ")}`);
    }
    lines.push(``);
  }

  const approvalRequired = active.filter(p => p.requiresApproval);
  if (approvalRequired.length > 0) {
    lines.push(`### Approval-Required Actions`, ``);
    for (const p of approvalRequired) {
      lines.push(`- **${p.action}**${p.resource ? ` on \`${p.resource}\`` : ""}: call \`verify_action\`, then pause for human approval before execution.`);
    }
    lines.push(``);
  }

  if (guidelines.length > 0) {
    lines.push(`### Guidelines`, ``);
    for (const g of guidelines) {
      lines.push(`- ${g}`);
    }
    lines.push(``);
  }

  lines.push(
    `### How to call \`verify_action\``,
    ``,
    `\`\`\``,
    `verify_action(action: string, vendor?: string, amount?: number)`,
    `// action: "purchase" | "access_data" | "browse_web" | "schedule" | "create_content" | ...`,
    `// vendor: the service or domain being accessed (e.g. "amazon.com", "gmail.com")`,
    `// amount: only for purchase actions`,
    `\`\`\``,
    ``,
    `---`,
    `*Updated ${timestamp} · Agent \`${agent.agentId}\` · [BehalfID](https://behalfid.com)*`
  );

  return lines.join("\n");
}

export function generateMcpJson(existing?: Record<string, unknown>): string {
  const base = existing ?? {};
  const servers = (base.mcpServers as Record<string, unknown> | undefined) ?? {};

  const updated = {
    ...base,
    mcpServers: {
      ...servers,
      behalfid: {
        type: "stdio",
        command: "behalf",
        args: ["mcp", "start"],
      },
    },
  };

  return JSON.stringify(updated, null, 2) + "\n";
}
