#!/usr/bin/env node
/*
 * Builds the scoped Lovable marketing utilities stylesheet.
 *
 * 1. Runs the Tailwind CLI over app/ds-tailwind.src.css, scanning the ported
 *    marketing components (which carry the source's LITERAL Tailwind classes).
 * 2. Scopes every emitted selector under `.ds` so nothing touches production
 *    styles (`:root` -> `.ds`, utilities -> `.ds <sel>`), leaving @keyframes
 *    and the design-system token layer untouched.
 *
 * Output: app/lovable-utilities.generated.css
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import postcss from "postcss";
import prefixer from "postcss-prefix-selector";

const root = new URL("..", import.meta.url).pathname;
const input = join(root, "app/ds-tailwind.src.css");
const raw = join(mkdtempSync(join(tmpdir(), "ds-css-")), "raw.css");
const output = join(root, "app/lovable-utilities.generated.css");

// 1. Compile Tailwind (theme + utilities, no preflight).
execFileSync(
  join(root, "node_modules/.bin/tailwindcss"),
  ["-i", input, "-o", raw, "--minify=false"],
  { stdio: "inherit" },
);

// 2. Scope under `.ds`.
const compiled = readFileSync(raw, "utf8");
const scoped = postcss([
  prefixer({
    prefix: ".ds",
    transform(prefix, selector, prefixedSelector) {
      // Token host: the design system lives on the .ds wrapper itself.
      if (selector === ":root" || selector === ":host") return prefix;
      if (selector === "*") return `${prefix} *`;
      // Leave html/body alone (no preflight is emitted, but be safe).
      if (selector === "html" || selector === "body") return selector;
      return prefixedSelector;
    },
  }),
]).process(compiled, { from: undefined }).css;

const banner =
  "/* GENERATED by scripts/build-ds-css.mjs — do not edit by hand.\n" +
  " * Real Tailwind output for the Lovable marketing components, scoped under `.ds`.\n" +
  " * Regenerate: npm run build:ds-css */\n";
writeFileSync(output, banner + scoped);
console.log(`Wrote ${output} (${scoped.length} bytes)`);
